conference.year=2027

quarkus.web-bundler.bundle.app=true
quarkus.hibernate-orm.schema-management.strategy=drop-and-create

%dev.quarkus.datasource.dev-ui.allow-sql=true

%cards-cli.quarkus.datasource.db-kind=h2
%cards-cli.quarkus.datasource.jdbc.url=jdbc:h2:mem:cards;DB_CLOSE_DELAY=-1
%cards-cli.quarkus.http.host=127.0.0.1
%cards-cli.quarkus.http.port=18080
%cards-cli.quarkus.banner.enabled=false
%cards-cli.quarkus.log.console.level=ERROR
