quarkus.web-bundler.bundle.app=true
quarkus.hibernate-orm.schema-management.strategy=drop-and-create

%dev.quarkus.datasource.dev-ui.allow-sql=true

# Production database
%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username=${DATABASE_USER:postgres}
%prod.quarkus.datasource.password=${DATABASE_PASSWORD:postgres}
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://postgresql:5432/speakercards
%prod.quarkus.hibernate-orm.database.generation=update

# Image configuration
quarkus.container-image.build=true
quarkus.container-image.group=markuseisele
quarkus.container-image.name=jchamps
quarkus.jib.base-jvm-image=registry.access.redhat.com/ubi9/openjdk-21:1.23
quarkus.jib.jvm-arguments=-agentlib:jdwp=transport=dt_socket\\,server=y\\,suspend=n\\,address=*:5005

# CSV input directory configuration
csv.input.directory=./csv-input

# CSV source file configuration
csv.source.file=SelectedWithSchedule.csv


